word_list =[
    "apple", "house", "car", "book", "water", "work", "school", "phone", "table", "friend",
    "eat", "drink", "sleep", "play", "read", "write", "talk", "walk", "run", "cook",
    "clean", "shop", "money", "time", "home", "family", "love", "happy", "sad", "angry",
    "tired", "busy", "free", "hello", "goodbye", "please", "thank", "sorry", "yes", "no",
    "now", "later", "tomorrow", "yesterday", "today", "morning", "evening", "night", "afternoon", "week",
    "month", "year", "sun", "moon", "star", "sky", "earth", "cloud", "rain", "snow",
    "wind", "storm", "thunder", "lightning", "fire", "ice", "hot", "cold", "warm", "cool",
    "day", "night", "morning", "evening", "afternoon", "time", "clock", "watch", "hour", "minute",
    "second", "new", "old", "young", "big", "small", "large", "long", "short", "high",
    "low", "fast", "slow", "quick", "easy", "hard", "difficult", "simple", "complex", "good",
    "bad", "right", "wrong", "true", "false", "happy", "sad", "angry", "excited", "bored",
    "scared", "afraid", "surprised", "shocked", "calm", "peaceful", "quiet", "noisy", "loud", "soft",
    "bright", "dark", "clear", "cloudy", "sunny", "rainy", "windy", "stormy", "foggy", "misty",
    "freezing", "hot", "warm", "cool", "dry", "wet", "thirsty", "hungry", "full", "tired",
    "awake", "asleep", "dream", "nightmare", "eat", "drink", "sleep", "wake", "rest", "relax",
    "work", "study", "learn", "teach", "listen", "speak", "talk", "write", "read", "type",
    "drive", "walk", "run", "swim", "dance", "sing", "play", "watch", "see", "look",
    "hear", "listen", "feel", "touch", "smell", "taste", "laugh", "cry", "smile", "frown",
    "fear", "hope", "wish", "want", "need", "like", "love", "hate", "enjoy", "dislike",
    "help", "hurt", "save", "destroy", "create", "build", "fix", "break", "open", "close",
    "start", "end", "finish", "begin", "stop", "continue", "move", "stay", "change", "grow",
    "shrink", "develop", "improve", "worsen", "win", "lose", "succeed", "fail", "try", "attempt",
    "achieve", "satisfy", "agree", "disagree", "understand", "confuse", "know", "forget", "remember", "think",
    "believe", "doubt", "imagine", "realize", "consider", "decide", "choose", "prefer", "allow", "forbid",
    "permit", "prohibit", "promise", "warn", "advise", "recommend", "offer", "invite", "refuse", "accept",
    "deny", "thank", "apologize", "forgive", "expect", "surprise", "belong", "own", "possess", "lend",
    "borrow", "return", "buy", "sell", "pay", "owe", "earn", "cost", "save", "spend", "invest",
    "waste", "need", "want", "wish", "desire", "request", "ask", "answer", "reply", "question",
    "mention", "say", "speak", "talk", "whisper", "shout", "yell", "scream", "mumble", "stammer",
    "pause", "silence", "noise", "sound", "voice", "word", "sentence", "phrase", "paragraph", "essay",
    "article", "story", "book", "novel", "poem", "song", "music", "movie", "film", "video",
    "picture", "photo", "painting", "drawing", "sketch", "sculpture", "art", "craft", "design", "fashion",
    "style", "trend", "idea", "concept", "thought", "mind", "brain", "intelligence", "knowledge", "wisdom",
    "truth", "fact", "lie", "fiction", "reality", "dream", "fantasy", "nightmare", "memory", "imagination"
]
